version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  build:
    commands:
      - npx prisma generate
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules
artifacts:
  files:
    - '**/*'
  base-directory: '.'
