version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - npx prisma generate
      - npm run build
artifacts:
  files:
    - '**/*'
    - '.ebextensions/**/*'
    - 'Procfile'
  base-directory: '.'
